server:
  port: 8092
spring:
  application:
    name: dubbo-rpc-consumer
    version: 1.0.0
  profiles:
    active: ${tenv:dev}
dubbo:
  registry:
    address: N/A
  #  address: ${REG_URL:zookeeper://127.0.0.1:2181}
  protocols:
    dubbo-rpc:
      name: dubbo
      port: ${PORT:8085}